language: python
python: 2.7
env:
- TOX_ENV=py27
- TOX_ENV=py32
- TOX_ENV=py33
- TOX_ENV=py34
- TOX_ENV=py35
install:
- pip install tox
script:
- tox -e $TOX_ENV
notifications:
  slack:
    secure: lm7XUGVMxiJMMzMHusSO0uFsWVsSATpq9WRLj5++EQrxF5KUQcocob0JL6KT2JvPI6qfxI9iVnVeePM1nmt9Mly52efSKjyiDDQBth5KnLFB/eHqpiXpl/fzaVYIiTR0lEQwYpfU2dPa2xaBjw8YguMNcbQdi4k9DRwj6Ax1wwvJQdglC+zBt+AcGxdsL7CDR/CWU3cvlc9Id+ED5Rm8myHknK6BJARyJTnRD0RtOLT2SCz4E6o/h2XaCxRwyNLwGSNbeIW1ieYtEitw442M0n5qAAIvxXJ9awRUTcAVxs9Bh+nLRdKTSeYqcOyCnwhCHQRG7iO7WIVio0VMrD/55JPXQgKNocTSGKcSskRKT1tnL3nmvJ7BVB8w5ghLMv0wdSVwoY7A56KSZpPP316RFTa8FVTVDxWtlu4ydDMsvtYWKBD2Wwym1CR2+c25Bdee1eIIogmpKEScJzKRquV+pEciu1geqTWuI/bxGOFFVYFRUdQmA1blnFHiFcrA/vqoouJNNVPY+yeyUQafveSy+Thz8Jvj87Ac0ZdLTnCoTwX9iJVTkJ5+JxsxF4BASdS2UXkktKpf2bnpTM86BO7BnFig4ou/OEa0a+i3vD35F/7XIuic+9vczhbccsLqtMewpTXu6kv9RoelB5ntjQx1JxEIvGgkIh5BBaG5gXzc5YE=
