cache:
  - C:\Users\appveyor\AppData\Local\pip\Cache\wheels

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    BUILD: "cmd /E:ON /V:ON /C .\\.appveyor\\build.cmd"

  matrix:
    # Pre-installed Python versions, which Appveyor may upgrade to
    # a later point release.
    # See: http://www.appveyor.com/docs/installed-software#python

    - PYTHON: "C:\\Python27"
      TOXENV: "py27"
      TOXPYTHON: "C:\\Python27\\python.exe"

    - PYTHON: "C:\\Python27-x64"
      TOXENV: "py27"
      TOXPYTHON: "C:\\Python27-x64\\python.exe"

    - PYTHON: "C:\\Python33"
      TOXENV: "py33"
      TOXPYTHON: "C:\\Python33\\python.exe"

    - PYTHON: "C:\\Python33-x64"
      DISTUTILS_USE_SDK: "1"
      TOXENV: "py33"
      TOXPYTHON: "C:\\Python33-x64\\python.exe"

    - PYTHON: "C:\\Python34"
      TOXENV: "py34"
      TOXPYTHON: "C:\\Python34\\python.exe"

    - PYTHON: "C:\\Python34-x64"
      DISTUTILS_USE_SDK: "1"
      TOXENV: "py34"
      TOXPYTHON: "C:\\Python34-x64\\python.exe"

    - PYTHON: "C:\\Python35"
      TOXENV: "py35"
      TOXPYTHON: "C:\\Python35\\python.exe"

    - PYTHON: "C:\\Python35-x64"
      TOXENV: "py35"
      TOXPYTHON: "C:\\Python35-x64\\python.exe"


init:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

install:
  - pip install -U codecov tox setuptools virtualenv wheel

build: off

test_script:
  - "%BUILD% tox -v"

after_test:
  - type C:\\projects\\astrodynamics\\.tox\\%TOXENV%\\log\\%TOXENV%-*.log
  - codecov --env APPVEYOR PYTHON TOXENV
  - "%BUILD% python setup.py bdist_wheel"

artifacts:
  # Archive the generated packages in the ci.appveyor.com build report.
  - path: dist\*

# Blacklist Travis branch used to test changes to config
branches:
  except:
    - travis
